---
title: "R Notebook"
output: html_notebook
---
Importing libraries
```{r}
library(ggplot2)
library(dplyr)
library(MCMCpack)
```
Read input and remove NA values

```{r}
data_cons<-read.csv('winemag-data-130k-v2.csv')
data_cons<-droplevels(na.omit(data_cons))
head(data_cons)
```

Filtering and grouping data
```{r}
#data_cons <- data_cons %>%
  #dplyr::mutate_at(vars(starts_with("region_1")), factor) 
  # %>% dplyr::mutate_at(vars(starts_with("region_1")), as.integer) 

data_cons <- data_cons %>% 
  dplyr::filter(country=='Italy'&price<20) %>%
  dplyr::select(points, region_1) %>%
  group_by(region_1) %>% 
  dplyr::mutate(n=n()) %>%
  dplyr::filter(n>=4)
dim(data_cons)
#dplyr::transmute_(data_cons, region_1=levels()) %>%
#data_cons <- dplyr::mutate(data_cons, region_1=levels(data_cons$region_1)[data_cons$region_1]) 
#data_cons_reg <- data_cons %>% group_by(region_1) %>% mutate(region_id=factor(region_1))
#dplyr::recode_factor(data_cons$region_id, region_id=as.integer(data_cons$region_id))
#levels(data_cons$region_1)["Vittoria"]

data_cons$region_id <- as.numeric(factor(data_cons$region_1))
data_cons$region_id <- dplyr::recode_factor(data_cons$region_id, region_id=data_cons$region_id)
#mapping the factor name for future use
#mapping<-data.frame(region_1=unique(data_cons$region_1))
#mapping$region_encoded=as.factor(as.integer(mapping$region_1))
#data_cons<-left_join(data_cons,mapping,by='region_1')[,c('region_encoded','points', 'n')]

head(data_cons)
```
```{r}
nlevels(data_cons$region_id)
```

```{r}
ggplot(data_cons) + geom_boxplot(aes(x = reorder(region_id, points, mean), points,
fill = reorder(region_id, points, mean)), show.legend=FALSE)
ggplot(data_cons, aes(x = reorder(region_id, region_id, length))) + stat_count()
ggplot(data_cons, aes(points)) + stat_bin(binwidth = 1)
```
Next
```{r}
ggplot(data.frame(size = tapply(data_cons$points, data_cons$region_id, length),
mean_score = tapply(data_cons$points, data_cons$region_id, mean)), aes(size, mean_score)) +
geom_point() + xlab("Region sample size") + ylab("Mean Score") +
ggtitle("Effect size versus sample size")
```
Next
```{r}
#function for sampling
compare_m_gibbs <- function(y, ind, mu0 = 85, tau0 = 1/49, 
                     a0 = 1, b0 = 50, alpha0 =1, beta0 = 50, maxiter = 500)
{
  ### starting values
  m <- nlevels(ind)
  ybar <- theta <- tapply(y, ind, mean)
  tau_w <- mean(1 / tapply(y, ind, var)) ##within group precision
  mu <- mean(theta)
  tau_b <-var(theta) ##between group precision
  n_m <- tapply(y, ind, length)
  alphan <- alpha0 + sum(n_m)/2
  ###
  
  ### setup MCMC
  theta_mat <- matrix(0, nrow=maxiter, ncol=m)
  mat_store <- matrix(0, nrow=maxiter, ncol=3)
  ###
  
  ### MCMC algorithm
  for(s in 1:maxiter) 
  {
    
    # sample new values of the thetas
    for(j in 1:m) 
    {
      taun <- n_m[j] * tau_w + tau_b
      thetan <- (ybar[j] * n_m[j] * tau_w + mu * tau_b) / taun
      theta[j]<-rnorm(1, thetan, 1/sqrt(taun))
    }
    
    #sample new value of tau_w
    ss <- 0
    for(j in 1:m){
      ss <- ss + sum((y[ind == j] - theta[j])^2)
    }
    betan <- beta0 + ss/2
    tau_w <- rgamma(1, alphan, betan)
    
    #sample a new value of mu
    taum <- m * tau_b + tau0
    mum <- (mean(theta) * m * tau_b + mu0 * tau0) / taum
    mu <- rnorm(1, mum, 1/ sqrt(taum)) 
    
    # sample a new value of tau_b
    am <- a0 + m/2
    bm <- b0 + sum((theta - mu)^2) / 2
    tau_b <- rgamma(1, am, bm)
    
    #store results
    theta_mat[s,] <- theta
    mat_store[s, ] <- c(mu, tau_w, tau_b)
  }
  colnames(mat_store) <- c("mu", "tau_w", "tau_b")
  return(list(params = mat_store, theta = theta_mat))
}

```

```{r}
fit2 <- compare_m_gibbs(data_cons$points, data_cons$region_id)
theta_hat <- apply(fit2$theta, 2, mean) ## get basic posterior summary
head(theta_hat)
#names(theta_hat) <- 1:100 ## keep track of different schools
#sort(theta_hat, decreasing = TRUE) ## which schools did best and worst?
```
```{r}
plot(as.mcmc(fit2$params))
acf(fit2$params)
raftery.diag(fit2$params)
```

```{r}
n = nlevels(data_cons$region_id)
theta_ci <- apply(fit2$theta, 2, quantile, prob = c(0.025, .975)) ## upper/lower bounds for thetas
df_error <- data.frame(lower = theta_ci[1, ], upper = theta_ci[2, ], mean = theta_hat,
region_id = factor(1:n))
ggplot(df_error, aes(x = reorder(region_id, mean), mean)) + geom_errorbar(aes(ymin = lower, ymax = upper))
```

```{r}
## reformat samples for ggplot
theta_df <- data.frame(samples = as.numeric(fit2$theta),
region = rep(1:ncol(fit2$theta), each = nrow(fit2$theta)))
ggplot(theta_df) + geom_boxplot(aes(x = reorder(region, samples, median), samples,
fill = reorder(region, samples, median)), show.legend=FALSE)
```

```{r}
ggplot(data.frame(size = tapply(data_cons$points, data_cons$region_id, length), theta_hat = theta_hat),
aes(size, theta_hat)) + geom_point()

ggplot(data.frame(ybar = tapply(data_cons$points, data_cons$region_id, mean), theta_hat = theta_hat),
aes(ybar, theta_hat)) + geom_point()
```

```{r}
result=data.frame(size = tapply(data_cons$points, data_cons$region_1, length),
                  theta_hat = theta_hat)
#result$region_final = row.names(result)
result = filter(result, theta_hat > 86.57671)
result
```

